<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="neil-PC" tests="2" failures="2" timestamp="24 Jul 2018 11:17:59 GMT" time="71.715" errors="0">
  <testcase name="test2" time="0.008" classname="class1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at class1.test2(class1.java:32)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.005" classname="class1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at class1.test3(class1.java:37)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite>
